name: Test and Build game

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    permissions:
      checks: write
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
          - WebGL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Cache Unity Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Hearth-Harm/HearthAndHarm
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: Hearth&Harm

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hearth&Harm-${{ matrix.targetPlatform }}-${{ env.date }}
          path: build/${{ matrix.targetPlatform }}
